# Generated by Django 6.0.2 on 2026-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/%Y/%m/%d/')),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('normal_probability', models.FloatField()),
                ('pneumonia_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Prediction History',
                'ordering': ['-created_at'],
            },
        ),
    ]
