# Generated by Django 6.0.2 on 2026-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='lung_area_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='lung_validated',
            field=models.BooleanField(default=False),
        ),
    ]
