# Generated by Django 6.0.2 on 2026-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionhistory_lung_area_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='segmented_image',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/%Y/%m/%d/segmented/'),
        ),
    ]
