# Generated by Django 6.0.2 on 2026-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_predictionhistory_segmented_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='gradcam_image',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/%Y/%m/%d/gradcam/'),
        ),
    ]
