# Generated by Django 6.0.2 on 2026-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_predictionhistory_gradcam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='grayscale_image',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/%Y/%m/%d/grayscale/'),
        ),
    ]
